-- disable trouble
return {
    { "nvim-neo-tree/neo-tree.nvim", enabled = false },
    { "akinsho/bufferline.nvim", enabled = false },
    { "nvimdev/dashboard-nvim", enabled = false },
    { "catppuccin/nvim", enabled = false },
    { "catppuccin", enabled = false },
    { "mini.ai", enabled = false },
    { "mini.comment", enabled = false },
    { "mini.pairs", enabled = false },
    { "mini.bufremove", enabled = false },
    { "mini.surround", enabled = false },
    { "mini.indentscope", enabled = false },
    { "flash.nvim", enabled = false },
    { "persistence.nvim", enabled = false },
    { "dressing.nvim", enabled = false },
    { "nui.nivm", enabled = false },
    { "noice.nvim", enabled = false },
    { "nvim-notify", enabled = false },
}
