-- disable trouble
return {
    { "nvim-neo-tree/neo-tree.nvim", enabled = false },
    { "akinsho/bufferline.nvim", enabled = false },
    { "nvimdev/dashboard-nvim", enabled = false },
    { "catppuccin/nvim", enabled = false },
    { "catppuccin", enabled = false },
    { "mini.comment", enabled = false },
    { "mini.surround", enabled = false },
    { "mini.pairs", enabled = false },
    { "mini.bufremove", enabled = false },
    { "mini.bufremove", enabled = false },
    { "MunifTanjim/nui.nvim", enabled = false },
    { "echasnovski/mini.indentscope", enabled = false },
    { "flash.nvim", enabled = false },
    { "persistence.nvim", enabled = false },
    { "dressing.nvim", enabled = false },
    { "nui.nivm", enabled = false },
    { "folke/noice.nvim", enabled = false },
    { "rcarriga/nvim-notify", enabled = false },
    { "echasnovski/mini.surround", enabled = false },
    { "folke/persistence.nvim", enabled = false },
    { "dstein64/vim-startuptime", enabled = false },
}
